name: Dispatch playground

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      smartcontracts:
        type: boolean
      devhub:
        type: boolean

jobs:
  job_smartcontracts:
    if: ${{ vars.GITHUB_EVENT_NAME }} == 'schedule' || ${{ inputs.smartcontracts == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
  job_devhub:
    if: ${{ vars.GITHUB_EVENT_NAME }} == 'schedule' || ${{ inputs.devhub == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
      - run: echo ${{ inputs.devhub == 'true' }}
      - run: echo ${{ inputs.devhub }}
